local keys = {
--	Character keys
["a"]=true, --	The A key
["b"]=true, --	The B key
["c"]=true, --	The C key
["d"]=true, --	The D key
["e"]=true, --	The E key
["f"]=true, --	The F key
["g"]=true, --	The G key
["h"]=true, --	The H key
["i"]=true, --	The I key
["j"]=true, --	The J key
["k"]="k", --	The K key
["l"]=true, --	The L key
["m"]=true, --	The M key
["n"]=true, --	The N key
["o"]=true, --	The O key
["p"]=true, --	The P key
["q"]=true, --	The Q key
["r"]=true, --	The R key
["s"]=true, --	The S key
["t"]=true, --	The T key
["u"]=true, --	The U key
["v"]=true, --	The V key
["w"]=true, --	The W key
["x"]=true, --	The X key
["y"]=true, --	The Y key
["z"]=true, --	The Z key
["0"]=true, --	The zero key
["1"]=true, --	The one key
["2"]=true, --	The two key
["3"]=true, --	The three key
["4"]=true, --	The four key
["5"]=true, --	The five key
["6"]=true, --	The six key
["7"]=true, --	The seven key
["8"]=true, --	The eight key
["9"]=true, --	The nine key
["space"]=true, --	Space key
["!"]=true, --	Exclamation mark key
["\""]=true, --	Double quote key
["#"]=true, --	Hash key
["$"]=true, --	Dollar key
["&"]=true, --	Ampersand key
["'"]=true, --	Single quote key
["("]=true, --	Left parenthesis key
[")"]=true, --	Right parenthesis key
["*"]=true, --	Asterisk key
["+"]=true, --	Plus key
[","]=true, --	Comma key
["-"]=true, --	Hyphen-minus key
["."]=true, --	Full stop key
["/"]=true, --	Slash key
[":"]=true, --	Colon key
[";"]=true, --	Semicolon key
["<"]=true, --	Less-than key
["="]=true, --	Equal key
[">"]=true, --	Greater-than key
["?"]=true, --	Question mark key
["@"]=true, --	At sign key
["["]=true, --	Left square bracket key
["\\"]=true, --	Backslash key
["]"]=true, --	Right square bracket key
["^"]=true, --	Caret key
["_"]=true, --	Underscore key
["`"]=true, --	Grave accent key
--	Numpad keys
["kp0"]=true, --	The numpad zero key
["kp1"]=true, --	The numpad one key
["kp2"]=true, --	The numpad two key
["kp3"]=true, --	The numpad three key
["kp4"]=true, --	The numpad four key
["kp5"]=true, --	The numpad five key
["kp6"]=true, --	The numpad six key
["kp7"]=true, --	The numpad seven key
["kp8"]=true, --	The numpad eight key
["kp9"]=true, --	The numpad nine key
["kp."]=true, --	The numpad decimal point key
["kp,"]=true, --	The numpad comma key
["kp/"]=true, --	The numpad division key
["kp*"]=true, --	The numpad multiplication key
["kp-"]=true, --	The numpad substraction key
["kp+"]=true, --	The numpad addition key
["kpenter"]=true, --	The numpad enter key
["kp="]=true, --	The numpad equals key
--	Navigation keys
["up"]=true, --	Up arrow key
["down"]=true, --	Down arrow key
["right"]=true, --	Right arrow key
["left"]=true, --	Left arrow key
["home"]=true, --	Home key
["end"]=true, --	End key
["pageup"]=true, --	Page up key
["pagedown"]=true, --	Page down key
--	Editing keys
["insert"]=true, --	Insert key
["backspace"]=true, --	Backspace key
["tab"]=true, --	Tab key
["clear"]=true, --	Clear key
["return"]=true, --	Return key
["delete"]=true, --	Delete key
--	Function keys
["f1"]=true, --	The 1st function key
["f2"]=true, --	The 2nd function key
["f3"]=true, --	The 3rd function key
["f4"]=true, --	The 4th function key
["f5"]=true, --	The 5th function key
["f6"]=true, --	The 6th function key
["f7"]=true, --	The 7th function key
["f8"]=true, --	The 8th function key
["f9"]=true, --	The 9th function key
["f10"]=true, --	The 10th function key
["f11"]=true, --	The 11th function key
["f12"]=true, --	The 12th function key
["f13"]=true, --	The 13th function key
["f14"]=true, --	The 14th function key
["f15"]=true, --	The 15th function key
["f16"]=true, --	The 16th function key
["f17"]=true, --	The 17th function key
["f18"]=true, --	The 18th function key
--	Modifier keys
["numlock"]=true, --	Num-lock key
["capslock"]=true, --	Caps-lock key
["scrolllock"]=true, --	Scroll-lock key
["rshift"]=true, --	Right shift key
["lshift"]=true, --	Left shift key
["rctrl"]=true, --	Right control key
["lctrl"]=true, --	Left control key
["ralt"]=true, --	Right alt key
["lalt"]=true, --	Left alt key
["rgui"]=true, --	Right gui key
["lgui"]=true, --	Left gui key
["mode"]=true, --	Mode key
--	Application keys
["www"]=true, --	WWW key
["mail"]=true, --	Mail key
["calculator"]=true, --	Calculator key
["computer"]=true, --	Computer key
["appsearch"]=true, --	Application search key
["apphome"]=true, --	Application home key
["appback"]=true, --	Application back key
["appforward"]=true, --	Application forward key
["apprefresh"]=true, --	Application refresh key
["appbookmarks"]=true, --	Application bookmarks key
--	Miscellaneous keys
["pause"]=true, --	Pause key
["escape"]=true, --	Escape key
["help"]=true, --	Help key
["printscreen"]=true, --	Printscreen key
["sysreq"]=true, --	System request key
["menu"]=true, --	Menu key
["application"]=true, --	Application key
["power"]=true, --	Power key
["currencyunit"]=true, --	Currency unit key
["undo"]=true, --	Undo key
}

return keys
